const maritalStatusOptions = [
  { value: 1, label: 'Single' },
  { value: 2, label: 'Married' },
  { value: 3, label: 'Widower' },
  { value: 4, label: 'Divorced' },
  { value: 5, label: 'Facto Union' },
  { value: 6, label: 'Legally Separated' },
];

const admissionOptions = [
  { value: 1, label: '1st phase - general contingent' },
  { value: 2, label: 'Ordinance No. 612/93' },
  { value: 5, label: '1st phase - special contingent (Azores Island)' },
  { value: 7, label: 'Holders of other higher courses' },
  { value: 10, label: 'Ordinance No. 854-B/99' },
  { value: 15, label: 'International student (bachelor)' },
  { value: 16, label: '1st phase - special contingent (Madeira Island)' },
  { value: 17, label: '2nd phase - general contingent' },
  { value: 18, label: '3rd phase - general contingent' },
  { value: 26, label: 'Ordinance No. 533-A/99, item b2) (Different Plan)' },
  { value: 27, label: 'Ordinance No. 533-A/99, item b3 (Other Institution)' },
  { value: 39, label: 'Over 23 years old' },
  { value: 42, label: 'Transfer' },
  { value: 43, label: 'Change of course' },
  { value: 44, label: 'Technological specialization diploma holders' },
  { value: 51, label: 'Change of institution/course' },
  { value: 53, label: 'Short cycle diploma holders' },
  { value: 57, label: 'Change of institution/course (International)' },
];

  const courses = [
    { code: 33, title: 'Biofuel Production Technologies' },
    { code: 171, title: 'Animation and Multimedia Design' },
    { code: 8014, title: 'Social Service (evening attendance)' },
    { code: 9003, title: 'Agronomy' },
    { code: 9070, title: 'Communication Design' },
    { code: 9085, title: 'Veterinary Nursing' },
    { code: 9119, title: 'Informatics Engineering' },
    { code: 9130, title: 'Equinculture' },
    { code: 9147, title: 'Management' },
    { code: 9238, title: 'Social Service' },
    { code: 9254, title: 'Tourism' },
    { code: 9500, title: 'Nursing' },
    { code: 9556, title: 'Oral Hygiene' },
    { code: 9670, title: 'Advertising and Marketing Management' },
    { code: 9773, title: 'Journalism and Communication' },
    { code: 9853, title: 'Basic Education' },
    { code: 9991, title: 'Management (evening attendance)' },
  ];

  const educationLevels = [
    { code: 1, title: 'Secondary education' },
    { code: 2, title: "Higher education - bachelor's degree" },
    { code: 3, title: 'Higher education - degree' },
    { code: 4, title: "Higher education - master's" },
    { code: 5, title: "Higher education - doctorate" },
    { code: 6, title: 'Frequency of higher education' },
    { code: 9, title: '12th year of schooling - not completed' },
    { code: 10, title: '11th year of schooling - not completed' },
    { code: 12, title: 'Other - 11th year of schooling' },
    { code: 14, title: '10th year of schooling' },
    { code: 15, title: '10th year of schooling - not completed' },
    { code: 19, title: 'Basic education 3rd cycle (9th/10th/11th year) or equiv.' },
    { code: 38, title: 'Basic education 2nd cycle (6th/7th/8th year) or equiv.' },
    { code: 39, title: 'Technological specialization course' },
    { code: 40, title: 'Higher education - degree (1st cycle)' },
    { code: 42, title: 'Professional higher technical course' },
    { code: 43, title: 'Higher education - master (2nd cycle)' },
  ];

const nationality = [
  { code: 1, title: 'Portuguese' },
  { code: 2, title: 'German' },
  { code: 6, title: 'Spanish' },
  { code: 11, title: 'Italian' },
  { code: 13, title: 'Dutch' },
  { code: 14, title: 'English' },
  { code: 17, title: 'Lithuanian' },
  { code: 21, title: 'Angolan' },
  { code: 22, title: 'Cape Verdean' },
  { code: 24, title: 'Guinean' },
  { code: 25, title: 'Mozambican' },
  { code: 26, title: 'Santomean' },
  { code: 32, title: 'Turkish' },
  { code: 41, title: 'Brazilian' },
  { code: 62, title: 'Romanian' },
  { code: 100, title: 'Moldova (Republic of)' },
  { code: 101, title: 'Mexican' },
  { code: 103, title: 'Ukrainian' },
  { code: 105, title: 'Russian' },
  { code: 108, title: 'Cuban' },
  { code: 109, title: 'Colombian' },
];

const educationLevelList = [
  { code: 1, title: 'Secondary Education - 12th Year of Schooling or Eq.' },
  { code: 2, title: "Higher Education - Bachelor's Degree" },
  { code: 3, title: 'Higher Education - Degree' },
  { code: 4, title: "Higher Education - Master's" },
  { code: 5, title: "Higher Education - Doctorate" },
  { code: 6, title: 'Frequency of Higher Education' },
  { code: 9, title: '12th Year of Schooling - Not Completed' },
  { code: 10, title: '11th Year of Schooling - Not Completed' },
  { code: 11, title: '7th Year (Old)' },
  { code: 12, title: 'Other - 11th Year of Schooling' },
  { code: 14, title: '10th Year of Schooling' },
  { code: 18, title: 'General Commerce Course' },
  { code: 19, title: 'Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.' },
  { code: 22, title: 'Technical-Professional Course' },
  { code: 26, title: '7th Year of Schooling' },
  { code: 27, title: '2nd Cycle of the General High School Course' },
  { code: 29, title: '9th Year of Schooling - Not Completed' },
  { code: 30, title: '8th Year of Schooling' },
  { code: 34, title: 'Unknown' },
  { code: 35, title: "Can't Read or Write" },
  { code: 36, title: 'Can Read Without Having a 4th Year of Schooling' },
  { code: 37, title: 'Basic Education 1st Cycle (4th/5th Year) or Equiv.' },
  { code: 38, title: 'Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.' },
  { code: 39, title: 'Technological Specialization Course' },
  { code: 40, title: 'Higher Education - Degree (1st Cycle)' },
  { code: 41, title: 'Specialized Higher Studies Course' },
  { code: 42, title: 'Professional Higher Technical Course' },
  { code: 43, title: 'Higher Education - Master (2nd Cycle)' },
  { code: 44, title: 'Higher Education - Doctorate (3rd Cycle)' },
];

const motherOccupationList = [
  { code: 0, title: 'Student' },
  { code: 1, title: 'Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers' },
  { code: 2, title: 'Specialists in Intellectual and Scientific Activities' },
  { code: 3, title: 'Intermediate Level Technicians and Professions' },
  { code: 4, title: 'Administrative Staff' },
  { code: 5, title: 'Personal Services, Security and Safety Workers, and Sellers' },
  { code: 6, title: 'Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry' },
  { code: 7, title: 'Skilled Workers in Industry, Construction, and Craftsmen' },
  { code: 8, title: 'Installation and Machine Operators and Assembly Workers' },
  { code: 9, title: 'Unskilled Workers' },
  { code: 10, title: 'Armed Forces Professions' },
  { code: 90, title: 'Other Situation' },
  { code: 99, title: '(blank)' },
  { code: 122, title: 'Health Professionals' },
  { code: 123, title: 'Teachers' },
  { code: 125, title: 'Specialists in Information and Communication Technologies (ICT)' },
  { code: 131, title: 'Intermediate Level Science and Engineering Technicians and Professions' },
  { code: 132, title: 'Technicians and Professionals, of Intermediate Level of Health' },
  { code: 134, title: 'Intermediate Level Technicians from Legal, Social, Sports, Cultural, and Similar Services' },
  { code: 141, title: 'Office Workers, Secretaries in General and Data Processing Operators' },
  { code: 143, title: 'Data, Accounting, Statistical, Financial Services and Registry-Related Operators' },
  { code: 144, title: 'Other Administrative Support Staff' },
  { code: 151, title: 'Personal Service Workers' },
  { code: 152, title: 'Sellers' },
  { code: 153, title: 'Personal Care Workers and the Like' },
  { code: 171, title: 'Skilled Construction Workers and the Like, Except Electricians' },
  { code: 173, title: 'Skilled Workers in Printing, Precision Instrument Manufacturing, Jewelers, Artisans, and the Like' },
  { code: 175, title: 'Workers in Food Processing, Woodworking, Clothing, and Other Industries and Crafts' },
  { code: 191, title: 'Cleaning Workers' },
  { code: 192, title: 'Unskilled Workers in Agriculture, Animal Production, Fisheries, and Forestry' },
  { code: 193, title: 'Unskilled Workers in Extractive Industry, Construction, Manufacturing, and Transport' },
  { code: 194, title: 'Meal Preparation Assistants' },
];

const fatherOccupationList = [
  { code: 0, title: 'Student' },
  { code: 1, title: 'Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers' },
  { code: 2, title: 'Specialists in Intellectual and Scientific Activities' },
  { code: 3, title: 'Intermediate Level Technicians and Professions' },
  { code: 4, title: 'Administrative Staff' },
  { code: 5, title: 'Personal Services, Security and Safety Workers, and Sellers' },
  { code: 6, title: 'Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry' },
  { code: 7, title: 'Skilled Workers in Industry, Construction, and Craftsmen' },
  { code: 8, title: 'Installation and Machine Operators and Assembly Workers' },
  { code: 9, title: 'Unskilled Workers' },
  { code: 10, title: 'Armed Forces Professions' },
  { code: 90, title: 'Other Situation' },
  { code: 99, title: '(blank)' },
  { code: 101, title: 'Armed Forces Officers' },
  { code: 102, title: 'Armed Forces Sergeants' },
  { code: 103, title: 'Other Armed Forces Personnel' },
  { code: 112, title: 'Directors of Administrative and Commercial Services' },
  { code: 114, title: 'Hotel, Catering, Trade, and Other Services Directors' },
  { code: 121, title: 'Specialists in Physical Sciences, Mathematics, Engineering, and Related Techniques' },
  { code: 122, title: 'Health Professionals' },
  { code: 123, title: 'Teachers' },
  { code: 124, title: 'Specialists in Finance, Accounting, Administrative Organization, Public and Commercial Relations' },
  { code: 131, title: 'Intermediate Level Science and Engineering Technicians and Professions' },
  { code: 132, title: 'Technicians and Professionals, of Intermediate Level of Health' },
  { code: 134, title: 'Intermediate Level Technicians from Legal, Social, Sports, Cultural, and Similar Services' },
  { code: 135, title: 'Information and Communication Technology Technicians' },
  { code: 141, title: 'Office Workers, Secretaries in General and Data Processing Operators' },
  { code: 143, title: 'Data, Accounting, Statistical, Financial Services, and Registry-Related Operators' },
  { code: 144, title: 'Other Administrative Support Staff' },
  { code: 151, title: 'Personal Service Workers' },
  { code: 152, title: 'Sellers' },
  { code: 153, title: 'Personal Care Workers and the Like' },
  { code: 154, title: 'Protection and Security Services Personnel' },
  { code: 161, title: 'Market-Oriented Farmers and Skilled Agricultural and Animal Production Workers' },
  { code: 163, title: 'Farmers, Livestock Keepers, Fishermen, Hunters, and Gatherers, Subsistence' },
  { code: 171, title: 'Skilled Construction Workers and the Like, Except Electricians' },
  { code: 172, title: 'Skilled Workers in Metallurgy, Metalworking, and Similar' },
  { code: 174, title: 'Skilled Workers in Electricity and Electronics' },
  { code: 175, title: 'Workers in Food Processing, Woodworking, Clothing, and Other Industries and Crafts' },
  { code: 181, title: 'Fixed Plant and Machine Operators' },
  { code: 182, title: 'Assembly Workers' },
  { code: 183, title: 'Vehicle Drivers and Mobile Equipment Operators' },
  { code: 192, title: 'Unskilled Workers in Agriculture, Animal Production, Fisheries, and Forestry' },
  { code: 193, title: 'Unskilled Workers in Extractive Industry, Construction, Manufacturing, and Transport' },
  { code: 194, title: 'Meal Preparation Assistants' },
  { code: 195, title: 'Street Vendors (Except Food) and Street Service Providers' },
];

const genderList = [
  { code: 1, title: 'Male' },
  { code: 0, title: 'Female' },
];

const daytimeAttendance = [
  { code: 1, title: 'Daytime' },
  { code: 0, title: 'Evening' },
];

const models = [
  { code: 7, title: 'Full Model'  },
  { code: 1, title: 'Simple features' },
  { code: 2, title: 'Basic features' },
  { code: 3, title: 'Basic with academic features' },
  { code: 4, title: 'Basic with financial features' },
  { code: 5, title: 'Basic with full academic' },
  { code: 6, title: 'Basic with financial and full academic' },
];

export { admissionOptions, maritalStatusOptions, nationality, courses, educationLevels,
 motherOccupationList, fatherOccupationList, educationLevelList, genderList, daytimeAttendance, models};